### ISSUE TITLE
bug: Some pixels aren't drawn

### ISSUE THREAD

**Issue by Cediwelli** [Rondrio/tictactoe#1]
The Images are not correctly drawn to the screen. See image below.

![tictactoe](https://user-images.githubusercontent.com/30579083/158786493-6f00d962-80b9-4800-8b57-5b27508ed3f8.png)

**Comment by Rondrio** [comment]
due to limitations of common terminals the engine I used is unable to can print every pixel in the texture. i hope this satisfy your issue :)

**Comment by Rondrio** [comment]
i will probably fix this in the next iteration
